### ISSUE TITLE
Config file details - nuscenes

### ISSUE THREAD

**Issue by naren2cmu** [dvlab-research/VoxelNeXt#5]
Hi, 

Thanks for your amazing repo. 

I found the following config files for nuscenes. Could you give more information about these config files? I want to use your model for detecting vehicles in nuscenes. 

<img width="264" alt="image" src="https://user-images.githubusercontent.com/113138659/227805219-fd1f18f8-00d2-47e8-b448-03980ef84927.png">

Thank you

**Comment by yukang2017** [comment]
Hi,

Thanks for your interests in our work.

For these config files,

`cbgs_dyn_pp_centerpoint.yaml` is the pointpillar-based backbone + CenterPoint head. You can refer to PointPillar [1] and CenterPoint [2] for more details.

`cbgs_pillar0075_res2d_centerpoint.yaml` is the pillarnet backbone + CenterPoint head. You can refer to PillarNet [3].

`cbgs_pp_multihead.yaml` is the pointpillar-based backbone + anchor-based head. You can refer to PointPillar[1] and SECOND [4].

`cbgs_second_multihead.yaml` is the voxel-based backbone + anchor-based head. You can refer to SECOND [4].

`cbgs_voxel0075_res3d_centerpoint.yaml` and `cbgs_voxel01_res3d_centerpoint.yaml` are exactly CenterPoint [2] with different voxel sizes.


Note that, these config files are not our method, VoxelNeXt. Because they also exist in the OpenPCDet codebase, I did not remove these files when I release the code. Our methods VoxelNeXt is [cbgs_voxel0075_voxelnext.yaml](https://github.com/dvlab-research/VoxelNeXt/blob/master/tools/cfgs/nuscenes_models/cbgs_voxel0075_voxelnext.yaml) and other config files with voxelnext names.


Regards,
Yukang Chen

[1] Alex H. Lang, Sourabh Vora, Holger Caesar, Lubing Zhou, Jiong Yang, Oscar Beijbom: PointPillars: Fast Encoders for Object Detection From Point Clouds. CVPR 2019: 12697-12705
[2] Tianwei Yin, Xingyi Zhou, Philipp Krähenbühl: Center-Based 3D Object Detection and Tracking. CVPR 2021: 11784-11793
[3] Guangsheng Shi, Ruifeng Li, Chao Ma: PillarNet: Real-Time and High-Performance Pillar-Based 3D Object Detection. ECCV (10) 2022: 35-52
[4] Yan Yan, Yuxing Mao, Bo Li: SECOND: Sparsely Embedded Convolutional Detection. Sensors 18(10): 3337 (2018)
